import type { RegisterMap } from "@/lib/schema/registerMap";
import { maskFor, shiftFor } from "@/lib/generate/hex";

export function generateHeader(map: RegisterMap): string {
  const dev = map.device.name.toUpperCase().replace(/[^A-Z0-9]/g, "_");
  const lines: string[] = [];
  lines.push(`/* Auto-generated by RegForge for ${map.device.name} (${map.device.vendor}). */`);
  lines.push(`#ifndef ${dev}_REGS_H`);
  lines.push(`#define ${dev}_REGS_H`);
  lines.push("");
  for (const r of map.registers) {
    lines.push(`/* ${r.name} @ ${r.address} (${r.access}) reset=${r.reset_value} - ${r.description} */`);
    lines.push(`#define ${dev}_${r.name.toUpperCase()} ${r.address}`);
    for (const f of r.fields) {
      const base = `${dev}_${r.name.toUpperCase()}_${f.name.toUpperCase()}`;
      lines.push(`#define ${base}_MASK ${maskFor(f.bits)}`);
      lines.push(`#define ${base}_SHIFT ${shiftFor(f.bits)}`);
    }
    lines.push("");
  }
  lines.push(`#endif /* ${dev}_REGS_H */`);
  lines.push("");
  return lines.join("\n");
}
