import type { RegisterMap } from "@/lib/schema/registerMap";
import { sanitizeComment } from "@/lib/generate/sanitize";

export interface DriverOutput { c: string; h: string; }

export function generateDriver(map: RegisterMap): DriverOutput {
  const slug = map.device.name.toLowerCase().replace(/[^a-z0-9]/g, "_");
  const guard = `${slug.toUpperCase()}_H`;
  const rw = map.registers.filter((r) => r.access !== "RO");

  const h: string[] = [];
  h.push(`/* Auto-generated by RegForge for ${map.device.name}. */`);
  h.push(`#ifndef ${guard}`, `#define ${guard}`, "");
  h.push(`#include <stdint.h>`, "");
  h.push(`/* Wire these to your MCU's I2C/SPI driver. Return 0 on success. */`);
  h.push(`int hal_${slug}_read(uint8_t reg, uint8_t *buf, uint16_t len);`);
  h.push(`int hal_${slug}_write(uint8_t reg, const uint8_t *buf, uint16_t len);`, "");
  h.push(`int ${slug}_init(void);`);
  h.push(`int ${slug}_read_reg(uint8_t reg, uint8_t *value);`);
  h.push(`int ${slug}_write_reg(uint8_t reg, uint8_t value);`, "");
  h.push(`#endif /* ${guard} */`, "");

  const c: string[] = [];
  c.push(`/* Auto-generated by RegForge for ${map.device.name}. */`);
  c.push(`#include "${slug}.h"`, `#include "${slug}_regs.h"`, "");
  c.push(`int ${slug}_read_reg(uint8_t reg, uint8_t *value) {`);
  c.push(`    return hal_${slug}_read(reg, value, 1);`);
  c.push(`}`, "");
  c.push(`int ${slug}_write_reg(uint8_t reg, uint8_t value) {`);
  c.push(`    return hal_${slug}_write(reg, &value, 1);`);
  c.push(`}`, "");
  c.push(`int ${slug}_init(void) {`);
  c.push(`    /* TODO: RegForge fills the ordered init sequence here (see Init Sequence panel). */`);
  for (const r of rw) {
    c.push(`    /* configure ${sanitizeComment(r.name)} (${r.address}) */`);
  }
  c.push(`    return 0;`);
  c.push(`}`, "");
  return { c: c.join("\n"), h: h.join("\n") };
}
