/* Auto-generated by RegForge for BMI270 (Bosch). */
#ifndef BMI270_REGS_H
#define BMI270_REGS_H

/* CHIP_ID @ 0x00 (RO) reset=0x24 - Chip identifier */
#define BMI270_CHIP_ID 0x00

/* PWR_CTRL @ 0x7D (RW) reset=0x00 - Enables sensors */
#define BMI270_PWR_CTRL 0x7D
#define BMI270_PWR_CTRL_ACC_EN_MASK 0x04
#define BMI270_PWR_CTRL_ACC_EN_SHIFT 2
#define BMI270_PWR_CTRL_GYR_EN_MASK 0x02
#define BMI270_PWR_CTRL_GYR_EN_SHIFT 1

#endif /* BMI270_REGS_H */
