/* Auto-generated by RegForge for BMI270. */
#include "bmi270.h"
#include "bmi270_regs.h"

int bmi270_read_reg(uint8_t reg, uint8_t *value) {
    return hal_bmi270_read(reg, value, 1);
}

int bmi270_write_reg(uint8_t reg, uint8_t value) {
    return hal_bmi270_write(reg, &value, 1);
}

int bmi270_init(void) {
    /* TODO: RegForge fills the ordered init sequence here (see Init Sequence panel). */
    /* configure PWR_CTRL (0x7D) */
    return 0;
}
