/* Auto-generated by RegForge for BMI270. */
#ifndef BMI270_H
#define BMI270_H

#include <stdint.h>

/* Wire these to your MCU's I2C/SPI driver. Return 0 on success. */
int hal_bmi270_read(uint8_t reg, uint8_t *buf, uint16_t len);
int hal_bmi270_write(uint8_t reg, const uint8_t *buf, uint16_t len);

int bmi270_init(void);
int bmi270_read_reg(uint8_t reg, uint8_t *value);
int bmi270_write_reg(uint8_t reg, uint8_t value);

#endif /* BMI270_H */
